---
- hosts: all
  connection: local
  serial: 1 
  gather_facts: no

  tasks:  
  - name: add known_hosts
    command: /usr/bin/ssh-keyscan -t ecdsa {{ ansible_host }} 
    register: keyscan 

  - lineinfile:
      name=~/.ssh/known_hosts
      create=yes
      line={{ item }} 
    with_items:
      - "{{ keyscan.stdout_lines }}"

