---
- hosts: all
  gather_facts: no
  tasks:

  - name: ssh-keygen ansible-server
    connection: local                 
    command: "ssh-keygen -b 2048 -t rsa -f /home/centos/.ssh/id_rsa -q -N ''"
    ignore_errors: yes
    run_once: true                   

  - name: import id_rsa.pub
    connection: local
    command: "cat /home/centos/.ssh/id_rsa.pub"
    register: id_pub
    run_once: true

  - name: add ansible-node authrized keys
    lineinfile:
      dest: /home/centos/.ssh/authorized_keys
      line: "{{ id_pub.stdout }}"
      
  - name: authorized_keys
    command: 'cat ~/.ssh/id_rsa.pub | ssh -i "~/.ssh/kepri-msa.pem" centos@{{ ansible_host }}  " cat - >> ~/.ssh/authorized_keys"' 

