---
- hosts: all
  connection: local
  serial: 1
  gather_facts: no

  tasks:
  - name: add_known_hosts
    include_tasks: "./hosts/add_known_hosts.yml"

- hosts: all
  serial: 1
  gather_facts: no
  tasks:

  - name: add_authorized_keys
    include_tasks: "./hosts/add_authorized_keys.yml"

  - name: add_all_host
    include_tasks: "./hosts/add_all_host.yml"
