---
- name: Install java
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Install open jdk
      command: "sudo yum install -y java-1.8.0-openjdk-devel.x86_64"
      become: yes

    - name: install wget 
      yum: name=wget state=present
      
    - name: Install git
      yum: 
        name: git
        state: present      

    - name: install openjdk 1.8.0
      yum: name=java-1.8.0-openjdk state=present

- name: Install hadoop
  hosts: all

  tasks:
    - name: Insert a line at the end of a file.
      blockinfile:
        path: /home/centos/.bashrc
        block: |
          export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.el7_7.x86_64
          export HADOOP_HOME=~/hadoop/
          export HADOOP_INSTALL=$HADOOP_HOME
          export HADOOP_MAPRED_HOME=$HADOOP_HOME
          export HADOOP_COMMON_HOME=$HADOOP_HOME
          export HADOOP_HDFS_HOME=$HADOOP_HOME
          export HADOOP_YARN_HOME=$HADOOP_HOME
          export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
          export PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

    - name: source ~/.bashrc
#      command: "source ~/.bashrc"
      shell: . /home/centos/.bashrc

    - name: check if hadoop is already downloaded 
      command: /usr/bin/test -e ~/hadoop-3.2.1.tar.gz
      ignore_errors: True
      register: hadoop_exists

    - name: download hadoop 3.2.1
      get_url:
         url=http://apache.claz.org/hadoop/common/hadoop-3.2.1/hadoop-3.2.1.tar.gz dest=/home/centos 
      when: hadoop_exists.rc != 0
 
    - name: check hadoop directory existence
      stat: path=~/hadoop-3.2.1
      register: hadoop_dir  

    - name: extract hadoop
      unarchive: src=~/hadoop-3.2.1.tar.gz dest=~ copy=no
      when: not hadoop_dir.stat.exists

    - name: create symbolic link
      file: src=~/hadoop-3.2.1 dest=~/hadoop state=link

    - name: hadoop conf core-site
      template: src=core-site.xml dest=~/hadoop/etc/hadoop

    - name: hadoop conf hdfs-site
      template: src=hdfs-site.xml dest=~/hadoop/etc/hadoop

    - name: hadoop conf mapred-site
      template: src=mapred-site.xml dest=~/hadoop/etc/hadoop

    - name: hadoop conf yarn-site
      template: src=yarn-site.xml dest=~/hadoop/etc/hadoop

    - name: workers
      template: src=workers dest=~/hadoop/etc/hadoop

    - name: Insert workers file.
      blockinfile:
        path: ~/hadoop/etc/hadoop/workers
        block: |
          hworker-1
          hworker-2
      become: no

    - name: Creates directory
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
      - ~/hadoop/pids
      - ~/hadoop/etc/hadoop/dfs/data
      - ~/hadoop/etc/hadoop/dfs/name
      become: no

    - name: format hadoop namenode
      command: " hadoop namenode -format "

#    - name: hadoop conf hadoop-env
#      template: src=hadoop-env.sh dest=~/hadoop/etc/hadoop

#    - name: hadoop conf yarn-env
#      template: src=yarn-env.sh dest=~/hadoop/etc/hadoop

#    - name: hadoop service config
#      copy: src=hadoop dest=/etc/init.d/hadoop mode=0777



